#!/bin/bash
# Script to create GitHub issues from the refactor plan
# Usage: ./scripts/create_refactor_issues.sh

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Check if gh is authenticated
if ! gh auth status &>/dev/null; then
    echo "Error: GitHub CLI is not authenticated. Please run 'gh auth login' first."
    exit 1
fi

# Function to create an issue
create_issue() {
    local title="$1"
    local body="$2"
    local labels="$3"
    
    echo "Creating issue: $title"
    gh issue create \
        --title "$title" \
        --body "$body" \
        --label "$labels"
    echo ""
}

# Issue 1: Clarify the public CLI API
create_issue \
    "Clarify the public CLI API" \
    "The command-line surface area lacks documentation. CLI modules expose many commands, but docstrings and MkDocs coverage are incomplete, making the workflow hard to navigate programmatically.

## Tasks

- [ ] Document commands via Google-style docstrings and MkDocs pages generated by \`mkdocstrings\`
- [ ] Add parameter validation for common options (paths, stages) and surface concise error messages

## Context

This addresses the finding that \"Command-line surface area lacks documentation: CLI modules expose many commands, but docstrings and MkDocs coverage are incomplete, making the workflow hard to navigate programmatically.\"" \
    "enhancement,documentation,cli"

# Issue 2: Decompose training orchestration
create_issue \
    "Decompose training orchestration" \
    "The training command responsibilities are tightly coupled. \`train\` mixes hardware inspection, configuration parsing, checkpoint selection, trainer wiring, and optional embedding generation in a single function, which reduces testability and makes error handling brittle.

## Tasks

- [ ] Extract hardware introspection, override parsing, checkpoint resolution, and Trainer creation into dedicated helper functions or classes in \`naics_embedder.utils\`
- [ ] Introduce a small orchestration object that returns a structured result (paths, metrics) for easier testing and reuse

## Context

This addresses the finding that \"Training command responsibilities are tightly coupled: \`train\` mixes hardware inspection, configuration parsing, checkpoint selection, trainer wiring, and optional embedding generation in a single function, which reduces testability and makes error handling brittle.\"" \
    "refactor,training,architecture"

# Issue 3: Isolate deprecated flows
create_issue \
    "Isolate deprecated flows" \
    "The sequential training pathway is deprecated but still prominent. The legacy sequential trainer remains alongside the primary flow without clear separation, increasing maintenance overhead and user confusion.

## Tasks

- [ ] Move sequential training into a dedicated module flagged as legacy, and gate it behind an explicit \`--legacy\` flag or environment variable
- [ ] Provide migration guidance in docs pointing users to the preferred curriculum implementation

## Context

This addresses the finding that \"Sequential training pathway is deprecated but still prominent: The legacy sequential trainer remains alongside the primary flow without clear separation, increasing maintenance overhead and user confusion.\"" \
    "refactor,technical-debt,documentation"

# Issue 4: Centralize warning configuration
create_issue \
    "Centralize warning configuration" \
    "Warning suppression is duplicated across multiple modules. Multiple modules suppress the same PyTorch Lightning warnings, leading to scattered configuration that can drift or hide useful signals.

## Tasks

- [ ] Create a \`naics_embedder.utils.warnings\` module that applies shared suppression settings once
- [ ] Replace scattered warning suppressions with imports from the centralized module
- [ ] Document the rationale for suppressed warnings

## Context

This addresses the finding that \"Warning suppression is duplicated: Multiple modules suppress the same PyTorch Lightning warnings, leading to scattered configuration that can drift or hide useful signals.\"" \
    "refactor,maintenance,code-quality"

# Issue 5: Harden data and tokenization inputs
create_issue \
    "Harden data and tokenization inputs" \
    "Tokenization and data access assumptions are implicit. Data paths and tokenization caches are inferred from configuration without validation, which can cause runtime surprises when files are missing or incompatible.

## Tasks

- [ ] Add lightweight pre-flight checks that confirm parquet schemas and tokenization cache compatibility before training or embedding generation begins
- [ ] Emit actionable remediation steps when inputs are missing or stale (e.g., regenerate cache, rerun preprocessing)
- [ ] Validate data paths and tokenization cache formats early in the pipeline

## Context

This addresses the finding that \"Tokenization and data access assumptions are implicit: Data paths and tokenization caches are inferred from configuration without validation, which can cause runtime surprises when files are missing or incompatible.\"" \
    "enhancement,data,validation,error-handling"

# Issue 6: Improve observability and outputs
create_issue \
    "Improve observability and outputs" \
    "Improve the observability of training runs and standardize output artifacts for better integration with downstream evaluation and documentation.

## Tasks

- [ ] Standardize logging fields (stage, experiment, device) across all training components
- [ ] Add summary artifacts (YAML/JSON) after training to feed downstream evaluation and MkDocs examples
- [ ] Ensure consistent log formatting and structured output" \
    "enhancement,logging,monitoring"

# Issue 7: Documentation integration
create_issue \
    "Documentation integration" \
    "Ensure comprehensive documentation coverage for all public APIs and improve discoverability of CLI workflows.

## Tasks

- [ ] Ensure all public functions, classes, and Typer commands include Google-style docstrings so \`mkdocstrings\` can render consistent API pages
- [ ] Add a short \"CLI quickstart\" section to the MkDocs site that links command groups to their generated documentation and explains common workflows (data prep, training, visualization)
- [ ] Verify that all API documentation is generated and accessible in the MkDocs site" \
    "documentation,enhancement"

echo "All issues created successfully!"

